### ISSUE TITLE
Wrong position when inside paper-drawer-panel main

### ISSUE THREAD

**Issue by makrolabs** [PolymerElements/paper-tooltip#10]
The tooltip gets twice the offset from the drawer, so the tooltip is positioned too far to the right. Same for paper-header-panel with the y coordinate being too high.

I think this happens because drawer main has position relative, and the paper tooltip uses position:absolute. This can be fixed by using position:fixed for the paper-tooltip.

**Comment by kungufli** [comment]
I can confirm this bug and also that adding position:fixed to the paper-tooltip will resolve it.

**Comment by notwaldorf** [comment]
I've tagged a new release which calculates the offset differently. Would you mind pulling the latest code and see if that fixes your probem? If not, could you add a snippet of code that reproes this? Thanks!

**Comment by kungufli** [comment]
@notwaldorf paper-tooltip 1.0.1 fixes this problem for me. Thank you.
