### ISSUE TITLE
Documentation doesn't explain default for "for"

### ISSUE THREAD

**Issue by akc42** [PolymerElements/paper-tooltip#117]
If the "for" property is not set, it appears (from reading the code) that the parent element (or host element if the parent is the shadow root) is the default, but that is not specified anywhere in the documentation.

**Comment by web-padawan** [comment]
It is specified, have a look at [this row](https://github.com/PolymerElements/paper-tooltip/blob/master/paper-tooltip.html#L22).

**Comment by akc42** [comment]
My bad.  I was looking all over for it and didn't notice it there.  However, I still think a default should be given against the "for" property so that it appears in the api docs

**Comment by notwaldorf** [comment]
Feel free to send a PR adding a comment to the `for` attribute: https://github.com/PolymerElements/paper-tooltip/blob/master/paper-tooltip.html#L124. Something like "if this is unset, then the tooltip will be centered to the parent node containing it"
