### ISSUE TITLE
wrong-position for simple paper-icon-button sibling

### ISSUE THREAD

**Issue by dsaronin** [PolymerElements/paper-tooltip#12]
relevant snippet is:
```
  <span>
     <paper-tooltip> Click to register printer as a cloudprint device </paper-tooltip>
    <paper-icon-button icon="cloud-queue">  </paper-icon-button>
  </span>
```
Three issues: 1) position is wrong; 2) show/hide is too sensitive; it's difficult to exactly position cursor to view the tooltip; 3) disappears too quickly

screenshot shows the displacement from element. I have been unsuccessful in trying to change the position with CSS. Even the MD spec shows tooltips being placed in close proximity to cursor.

![screenshot from 2015-07-23 12 11 05](https://cloud.githubusercontent.com/assets/410380/8859872/ee49e428-3134-11e5-9df5-9301a3b9d979.png)

**Comment by notwaldorf** [comment]
I've just tagged a new release, which may have fixed this. Would you mind pulling the latest code and see if it's better?

If it's still not fixed, would you mind telling me what the styles on the `span`'s parent are? The tooltip should definitely not be displayed where it is, it's just confused about its parent's position :(

**Comment by dsaronin** [comment]
I'll check it out and let you know; a work-around I was using was to use
negative margin-top and negative margin-left as compensation.

**Comment by dsaronin** [comment]
It's better; but still has issues. see attached screenshot. The tooltip is too far to the left, and is either being cut off by the menu-drawer panel (screenshot) or for a narrow screen, the left margin.
![screenshot from 2015-07-28 15 54 45](https://cloud.githubusercontent.com/assets/410380/8946002/6cec85b4-3541-11e5-8a75-51c96f0d70e4.png)

**Comment by notwaldorf** [comment]
@dsaronin There is a `fit-to-visible-bounds` attribute available on tooltips that will clip to the available parent, and should solve the problem above. Please re-open if it's still happening.

**Comment by dsaronin** [comment]
thanks

**Comment by dsaronin** [comment]
I still do not think it is working correctly. Re the new attribute, the description states: "If true, no parts of the tooltip will ever be shown offscreen." The two screenshots show that the tooltip is still being displayed offscreen to the right; and the other screenshot shows the html element in the page.

![screenshot from 2015-10-20 16 37 08](https://cloud.githubusercontent.com/assets/410380/10624048/9da473f2-7749-11e5-9de2-2bb2f2fa424b.png)
![screenshot from 2015-10-20 16 38 24](https://cloud.githubusercontent.com/assets/410380/10624047/9da28286-7749-11e5-8e14-44c0486debcc.png)
