### ISSUE TITLE
Unable to change 'font-size'

### ISSUE THREAD

**Issue by woodfox** [PolymerElements/paper-tooltip#123]
This was discussed in [Issue 57](https://github.com/PolymerElements/paper-tooltip/issues/57) before, but the [example](http://jsbin.com/vomicaw/edit?html,output) to set font-size doesn't work now.

      paper-tooltip.giant {
        --paper-tooltip: {
          font-size: 40px;
        }
      }

**Comment by KeithHenry** [comment]
There is a new example at http://jsbin.com/buxejiq/edit?html,output that works.

I don't think this issue is extant in the code.

**Comment by notwaldorf** [comment]
Closing, as this seems to work fine.

**Comment by RemiLelaidier** [comment]
The example look to be broken
