### ISSUE TITLE
paper-tooltip position attribute?

### ISSUE THREAD

**Issue by Sinjins** [PolymerElements/paper-tooltip#20]
It seems that the 'positioning' of the paper-tooltip element is a commonly brought up issue here.  Is there a possibility that a 'position' property/attribute could be reintroduced for this element, similar to how core-tooltip functioned previously?

**Comment by notwaldorf** [comment]
Yup! It's at the top of the PR queue :)

**Comment by m4b** [comment]
Would this position attribute work to anchor the tooltip at an x/y mouse coordinate?  I.e., I have "objects" inside a `<canvas>`, but they're inaccessible due to obvious reasons, whereas an x/y coordinate would suffice to anchor the tooltip inside the canvas, "on" the object.
