### ISSUE TITLE
Using `for` in `dom-repeat` only works for the first element

### ISSUE THREAD

**Issue by Mygod** [PolymerElements/paper-tooltip#21]

**Comment by notwaldorf** [comment]
@Mygod Do you have a snippet of the code that you're using? I think you might be assigning the same `for` element to all the tooltips.

**Comment by Mygod** [comment]
Yes. Is there a better way to do this?

Here's the snippet:

    <template is="dom-repeat" items="[[items]]">
        <tr>
            <td>
                <paper-icon-button id="btn" icon="delete"></paper-icon-button>
                <paper-tooltip for="btn">Delete</paper-tooltip>
            </td>
        </tr>
    </template>

**Comment by eximius313** [comment]
until this issue is resolved: https://github.com/Polymer/polymer/issues/2182 you have to create computation method where you concatenate ```btn_``` with ```item.id```

**Comment by notwaldorf** [comment]
Yup @eximius313 is correct. Your code is binding all tooltips to the first `btn` id, which is incorrect.
