### ISSUE TITLE
Some way to disable the tooltip

### ISSUE THREAD

**Issue by govis** [PolymerElements/paper-tooltip#23]
In case of a dynamic tooltip content it might be left empty if there's no hint available. It will still show a small grey rectangle though. Empty tooltip should not be shown. Some way to disable it might also be useful.

**Comment by govis** [comment]
Also, if rendered by a conditional template and condition changes from true to false it seems to be giving the following error: 
<code>
TypeError: Cannot read property 'getBoundingClientRect' of null
File name:      	paper-tooltip.html
Line number:       	212
</code>

**Comment by notwaldorf** [comment]
I am adding a fix to not show a tooltip if its contents is empty. In the meantime, I think that if you add `hidden` to the tooltip, it will not be displayed:
```
<paper-tooltip hidden>Atomic number: 8</paper-tooltip>
```

**Comment by govis** [comment]
Thanks for looking into this. I tried data-binding the hidden attribute: <code>hidden$="[[_disableTooltip(...)]]"</code> and it seems to be causing above error as well when condition changes.
