### ISSUE TITLE
Tooltip zdepth visual card issue

### ISSUE THREAD

**Issue by JesterXL** [PolymerElements/paper-tooltip#27]
The tooltip seems to be too low, the card's action area line is covering the tooltip. At least I think it is, pretty sure it's not the transparency. Same with the button in the card's action area. I made the button obnoxious in the screenshot so you can see it. Setting z-index doesn't seem to help. I've tried moving her out of the paper-card, but then I get an exception that she can't find the target. Using v1.0.2 of tooltip.

![screen shot 2015-08-16 at 10 59 50 am](https://cloud.githubusercontent.com/assets/424737/9293792/6c202f22-4406-11e5-80c9-d644611d2cba.png)

**Comment by kungufli** [comment]
This is a problem similar to https://github.com/PolymerElements/paper-tooltip/issues/18. It seems `paper-tooltip` still have some problems related to `z-index`.

**Comment by indolering** [comment]
I'm having similar problems with iron-list.  I couldn't get the following example to render in JSBin, but you should be able to c/p it to your favorite editor and view it locally.  Maybe someone can get it working : )

http://jsbin.com/cetabu/2/edit?html,output

**Comment by notwaldorf** [comment]
First, I have fixed up the JSBin to work: http://jsbin.com/nexebu/edit?html,output

Second, let's add @blasten to this conversation because he's seen every which way `iron-list` is used. I think what's happening is that each of the center elements has the same z-index, and because they're added one after another, the order of items in the list is the stack order. The tooltip unfortunately belongs to one of these `class="block` divs, and the next one will stomp over it.

I would maybe try giving them all id's, and using the `<paper-tooltip for="someId">` incantation, though I'm not super sure how that works with `iron-list`

@blasten: WDYT?

**Comment by indolering** [comment]
@notwaldorf's you commented out a background color which visually blocks the tooltip.  Here is one with the background:  http://jsbin.com/hisasi/1/edit?html,output

@notwaldorf I'm afraid that the root problem might be that most web developers don't know anything about the layering system and will simply expect your tooltip to behave like a real tooltip and visually float above other elements.  If there is no magic you can apply to force your tooltip above other elements, perhaps you could add a section to the documentation....

> I would maybe try giving them all id's, and using the <paper-tooltip for="someId"> incantation, though I'm not super sure how that works with iron-list

In my real code, each item from iron-list is in a custom element.

**Comment by blasten** [comment]
@indolering 
iron-list uses the `transform` property in every tile which will create a stacking context:  https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

As a result, layers positioned absolute inside the tiles will appear on top or under the tiles around. To solve this problem, you would need to attach a single tooltip to the the parent of iron-list and then dynamically set the target of the tooltip from a mouse event handler. Is it possible to set the target to an element reference programmatically? @notwaldorf

**Comment by notwaldorf** [comment]
@blaseten yup, you get do `someTooltip.for = 'someId'` after render as well. When `for` changes, the tooltip's target is recomputed.

**Comment by indolering** [comment]
> you get do someTooltip.for = 'someId' after render as well. When for changes, the tooltip's target is recomputed.

And if the target in question is within the shadow dom of an element?

**Comment by notwaldorf** [comment]
@indolering I'm not sure what you mean. Do you mean something like this?
```
<paper-tooltip for="foo"></paper-tooltip>
<some-element></some-element>
```
Where `<some-element>` has a shadow child named `foo`? That's not possible. Shadow boundaries are deal breakers.

**Comment by indolering** [comment]
@notwaldorf Yup : (

Not sure this ticket should still be open?

**Comment by GabiAxel** [comment]
I found a workaround for the issue with iron-list described by @indolering allowing the tooltip elements to remain inside the items: set the items with descending z-index, which will make the tooltips in each item to be displayed over the subsequent items.

```html
<iron-list items="[[_items]]>
  <template>
    <div style$="[[_getIndexStyle(index)]]">
      <!-- tooltips... -->
    </div>
  </template>
</iron-list>
```
```javascript
_getIndexStyle: function(index) {
  return 'z-index:' + (this._items.length - index);
}
```

**Comment by indolering** [comment]
@GabiAxel Ahh, I think I'm already using a variation of that hack in that my even numbered elements don't have a background color.   Would be nice to codify this into iron-list, even if it's just in the documents section.

**Comment by notwaldorf** [comment]
Closing this, since this is not really an issue with paper-tooltip anymore
