### ISSUE TITLE
Anchoring element in dom-repeat does not work with for="id" attribute

### ISSUE THREAD

**Issue by makrolabs** [PolymerElements/paper-tooltip#28]
I think using for="id" as an anchnor is not optimal because when we put this in a dom-repeat loop then there are multiple elements with the same id. Maybe a syntax like this would help:

    <paper-tooltip-container>
    <div class="tooltip-anchor">Hover Me</div>
    <paper-tooltip>I am a tooltip</paper-tooltip>
    </paper-tooltip-container>

**Comment by notwaldorf** [comment]
This should already work. If you look in the demo (https://github.com/PolymerElements/paper-tooltip/blob/master/demo/index.html#L82), the tooltip will also appear if it's placed in a `display: inline-block` div. Does that work for you?

**Comment by notwaldorf** [comment]
Closing this, since there's no answer and it's a pretty old issue. Please re-open if it's still happening.
