### ISSUE TITLE
Tooltip is being drawn under other elements with elevation

### ISSUE THREAD

**Issue by Mygod** [PolymerElements/paper-tooltip#3]
Using `z-index: 999` to fix this problem for now.

**Comment by gertcuykens** [comment]
![image](https://cloud.githubusercontent.com/assets/863731/8665870/9eb02ece-29e9-11e5-85ca-a805b26aef5a.png)

**Comment by Mygod** [comment]
Umm when is there going to be a new release?

**Comment by notwaldorf** [comment]
@Mygod There's no releases that have additional fixes for this problem. There's a PR in flight that adds position attributes to the tooltip, and there will be a release after that.

**Comment by Mygod** [comment]
Thanks for the fix.
