### ISSUE TITLE
paper-tooltip inside paper-item inherits the line-height

### ISSUE THREAD

**Issue by RoXuS** [PolymerElements/paper-tooltip#36]
Hello Polymer Team !

We have a problem with a paper-tooltip inside a paper-item.

The paper-tooltip inherits the `line-height: 24px;` of the paper-item so it no longer meets the specifications of the material design.

![image](https://cloud.githubusercontent.com/assets/3296671/10258226/1454662e-695d-11e5-88d9-5e99101cb3fc.png)
![image](https://cloud.githubusercontent.com/assets/3296671/10258259/4c4d5ba8-695d-11e5-8244-f3e44ad9102a.png)

**Comment by notwaldorf** [comment]
Hiya! Can you post a snippet of your code? How are you using the tooltip _inside_ the `paper-item`?

**Comment by RoXuS** [comment]
Thanks for your time.

Here the code of the previous screens :

```
<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../paper-item/paper-item.html">
<link rel="import" href="../paper-tooltip/paper-tooltip.html">
<link rel="import" href="../paper-item/paper-item-body.html">

<dom-module id="dt-paper-item">
  <template>
    <paper-item id="test" on-tap="onSelect">
      <paper-item-body>
        <div>
          <span id="test1">
            Test1
          </span>
          <paper-tooltip for="test1">
            TestTooltip
          </paper-tooltip>
        </div>
      </paper-item-body>
    </paper-item>
  </template>
</dom-module>
```

**Comment by notwaldorf** [comment]
Ah, got it, of course. Sending out a PR now.

**Comment by RoXuS** [comment]
Thx !
