### ISSUE TITLE
Visibility should be configurable

### ISSUE THREAD

**Issue by indolering** [PolymerElements/paper-tooltip#40]
I'm using tooltip primarily for showing error messages so I don't want the tooltip to display unless there is an error and, when there is an error, I want the tooltip to remain in place until the error is resolved.  The tooltip should have some sort of config for disabling hover visibility (maybe `show="hover|click|etc"`) and setting a timeout (maybe `element.show(timeout)`).

**Comment by notwaldorf** [comment]
I am not sure `tooltip` is meant to be used for that. It's meant to be a contextual help for the element it's attached to (see https://www.google.com/design/spec/components/tooltips.html), similar to how `title` works on native elements.

It sounds like you want to build your own custom element, maybe based on `paper-tooltip`, that does what you want (it sounds like you don't care about hovering at all, so you wouldn't need any of the listeners, and just need two `show`/`hide` methods). What do you think?

/cc @tjsavage to double check if this should be a feature we should consider

**Comment by indolering** [comment]
@notwaldorf To be perfectly frank, the native validity API should just offer more control over displaying error messages.  But it would be nice if the tooltip would offer this functionality.

**Comment by tjsavage** [comment]
Agreed with @notwaldorf - the behavior of the `paper-tooltip` is limited to displaying contextual information on hover and focus. The goal with the `paper-elements` is to provide rails to build perfectly-to-spec material design apps, so we try to keep the behavior limited to to what the MD spec dictates.

The behavior you describe seems perfectly reasonable though. I think @notwaldorf is right - you're really looking for a new element. Best bet might be to fork `paper-tooltip` and add in the API surface that you need, but keep the styling. Should hopefully be relatively straightforward (please ask on Slack or Stackoverflow if it's not!) but I think we'll want to keep that behavior separate from the `paper-tooltip` element itself.

**Comment by mfdeveloper** [comment]
I need a component with this feature. @indolering, What did you do? Created a custom separated component?
