### ISSUE TITLE
How to make the tooltip stay with the link inside it and make the link clickable

### ISSUE THREAD

**Issue by harshakakumanu** [PolymerElements/paper-tooltip#44]
<paper-tooltip><a href="activate.html">Activate</a></paper-tooltip>

**Comment by notwaldorf** [comment]
Not sure what this issue means, closing.

**Comment by notwaldorf** [comment]
If you mean that you want to be able to click on a link inside a `paper-tooltip`, that is not supported behaviour. A tooltip just offers extra information about a control (like the native `title` attribute), and cannot be interacted with.

**Comment by harshakakumanu** [comment]
Oh okay. No problem. Thank you. I will do it manually by using hover:
