### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by garrettn** [PolymerElements/paper-tooltip#56]
There have been [quite a few changes](https://github.com/PolymerElements/paper-tooltip/compare/v1.1.1...master) to this component since v1.1.1 was released. Any chance these could be pushed in a new release soon? I particularly need the fix from 97beae638385ca5055daa0a58d20524d3e841d30. Thanks.

**Comment by notwaldorf** [comment]
Sorry about that! Just released `1.1.2`
