### ISSUE TITLE
If position="left" tooltips are shown first when hovering the second time

### ISSUE THREAD

**Issue by silentHoo** [PolymerElements/paper-tooltip#64]
### Description
I've the following situation where I use AngularJS and the `<paper-tooltip>` within ngRepeat:

````
<ul id="todo-list">
  <li ng-repeat="todo in todos | filter:statusFilter track by $index" ng-class="{completed: todo.completed, editing: todo == editedTodo}">
    <div class="view">
      <input class="toggle" type="checkbox" ng-model="todo.completed" ng-change="toggleCompleted(todo)">
      <div style="display: flex; justify-content: space-between">
          <label class="todo-label one-line-ellipsis" ng-dblclick="editTodo(todo)">
              {{todo.title}}
          </label>
          <div style="display: flex; align-items: center">
              <label ng-attr-id="todo-tooltip-{{$index}}" class="todo-deadline">{{todo.deadline | amDateFormat: dateFormat }}</label>
              <paper-tooltip class="todo-createdAt-tooltip" ng-attr-for="todo-tooltip-{{$index}}" position="left" animation-delay="0">
                  Created at {{todo.createdAt | amDateFormat: dateFormat }}
              </paper-tooltip>
        </div>
      </div>
      <button class="destroy" ng-click="removeTodo(todo)"></button>
    </div>
  </li>
</ul>
````

I set the id dynamically via `ng-attr-<attrName>` to avoid using the not interpolated strings. 

### Expected outcome

Should be positioned on the left side.

### Actual outcome

Here are some clips which demonstrate this behaviour:

![add_todo](https://cloud.githubusercontent.com/assets/1610894/14670269/a2a50e88-06ec-11e6-93d1-40a60dddb12b.gif)
![add_one_more_todo](https://cloud.githubusercontent.com/assets/1610894/14670285/b337612e-06ec-11e6-977c-51fcc83f4403.gif)
![reload_page_works](https://cloud.githubusercontent.com/assets/1610894/14670294/bdbd67d8-06ec-11e6-9ffd-083a83887fe4.gif)

Works pretty well for `position="right"`:

![position_right](https://cloud.githubusercontent.com/assets/1610894/14670314/d6316d82-06ec-11e6-8478-056150e6d642.gif)

If I set the positions to something other (right, top, bottom) it works as expected. But only with position left it does nothing. I hadn't the time to make an in-depth look into the paper-tooltip code. But I'm pretty sure that my code should work. It's just an experiment, so I'm happy about any suggestions 👍

**Comment by notwaldorf** [comment]
Hmm, I can't reproduce this: http://jsbin.com/keyehid/edit?html,output

If you don't have any angular things in it, can you reproduce the bug? In that case, please please post a jsbin with your code, so that we can take a look at it, and we'll re-open this issue.
