### ISSUE TITLE
Tooltip under iron-icon

### ISSUE THREAD

**Issue by DeadcatDev** [PolymerElements/paper-tooltip#66]
As on screen (no additional styling), how to change z-index of it?

![paper-tooltip](https://cloud.githubusercontent.com/assets/15237149/14895032/ed9bb118-0d76-11e6-8d7b-814c0b63720c.jpg)

**Comment by J3remyD** [comment]
Hi @DeadcatDev , it's suppose to work as it is, can you provide a sample of the code that produces this

**Comment by notwaldorf** [comment]
Closing, since there's no jsbin with repro steps. Please re-open if there's some code we can take a look at
