### ISSUE TITLE
Scrollable content

### ISSUE THREAD

**Issue by J3remyD** [PolymerElements/paper-tooltip#76]
Hi,

I'm facing a use case in which I need to put a reasonable amount of content in a tooltip, but unfortunately my button that holds the tooltip is in tile so the tooltip doesn't have enough space to display the whole content, and I was hopping maybe we could have a scrollable content, what do you say ?

Cheers,
Jeremy

**Comment by notwaldorf** [comment]
According to the [spec](https://www.google.com/design/spec/components/tooltips.html) tooltips are meant to convey a small amount of extra information about that control. I don't think it's in this element's scope to have complex content, so you might want to make a new element that is based on paper-tooltip that meets your requirements.
