### ISSUE TITLE
<paper-tooltip manual-mode> closes on mouseenter (should only close on .hide())

### ISSUE THREAD

**Issue by danbeam** [PolymerElements/paper-tooltip#85]
### Description

`<paper-tooltip manual-mode>` still hides on `mouseenter` of the tooltip

### Expected outcome
If in `manual-mode`, I must call `.hide()` to close.

### Actual outcome
Because of [this code](https://github.com/PolymerElements/paper-tooltip/blob/master/paper-tooltip.html#L209):

```js
listeners: {
  'mouseenter': 'hide',
},
```

the typical `if (this.manualMode)` checks are skipped and the tooltip is closed.

/cc @tjsavage @noms I know that this element is unmaintained, but I need a reviewer or merger eventually for a PR I'll send.

**Comment by danbeam** [comment]
welp, didn't mean to commit that directly to this branch.

**Comment by notwaldorf** [comment]
The change is fine, I'm super confused as to how you landed it on master?

**Comment by danbeam** [comment]
i accidentally the master directly

![](http://i.imgur.com/ZVKccoS.png)

**Comment by JanMiksovsky** [comment]
@danbeam As I read this, dynamic changes to `manualMode` won't enable/disable the auto-hide behavior as expected.

**Comment by danbeam** [comment]
@JanMiksovsky yeah, you're right.  that was an issue before as well, though.

@notwaldorf maybe I'll send another PR to fix (instead of committing directly to master :stuck_out_tongue_closed_eyes:)
