### ISSUE TITLE
2.0-preview branch

### ISSUE THREAD

**Issue by naoak** [PolymerElements/paper-tooltip#93]
It seems this element does not have the 2.0-preview branch yet. Any schedule for migrating to v2? Thanks.

**Comment by TomK** [comment]
I've created a 2.0 compatible version here:
https://github.com/TomK/paper-tooltip/tree/2.0-preview

I'm unable to create a PR as the branch does not exist yet (you can't PR to a new branch)

**Comment by notwaldorf** [comment]
Branch exists :)
